api-version: 1

image:
  pullPolicy: IfNotPresent
  tag: 1.0.0

labels:
  environment: staging
  framework: play2
  instance: default
  repo: scala-play-api
  task: service

ports:
  nodePort: false

resources:
  limits:
    memory: 350Mi
  requests:
    cpu: 200m

strategy:
  maxUnavailable: 0
  maxSurge: 1

replicas: 1
